apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: myapp
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer

